
version: '3.8'

services:

  db:

    image: mysql:8.0


    container_name: jdbc-mysql


    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'anime_store'

    volumes:
      - jdbc_data:/var/lib/mysql

# Declaração do volume para que o Docker o gerencie.
volumes:
  jdbc_data: