
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - jdbc_tributino_data:/var/lib/mysql

volumes:
  jdbc_tributino_data: